### ISSUE TITLE
Error in Kotlin

### ISSUE THREAD

**Issue by abcghy** [markzhai/DataBinding-RecyclerViewAdapter#9]
When I use Kotlin, and settle everything down. I found BR.java not exist. Don't know if it's kapt's problem or this repo's. Could you please give an solution?

**Comment by markzhai** [comment]
@abcghy I don't use Kotlin, you may check what's wrong with data binding in kotlin

**Comment by abcghy** [comment]
Here's the error.
```
FATAL EXCEPTION: main
Process: com.example.sakura.gailvlun, PID: 25592
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/markzhai/recyclerview/BR;
    at com.github.markzhai.recyclerview.BaseViewAdapter.onBindViewHolder(BaseViewAdapter.java:37)
    at com.github.markzhai.recyclerview.BaseViewAdapter.onBindViewHolder(BaseViewAdapter.java:14)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
    at android.view.View.layout(View.java:16669)
    at android.view.ViewGroup.layout(ViewGroup.java:5440)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2207)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
    at android.view.Choreographer.doFrame(Choreographer.java:608)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
    at android.os.Handler.handleCallback(Handler.java:742)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.refl
```

**Comment by song314** [comment]
I meet the same compile error in Kotlin : 
`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.markzhai.recyclerview.BR" on path: DexPathList`
